app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\SecurityController::register

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

# Ajoutez ici les autres routes pour les différentes parties de votre CRM

